# Generated by Django 3.1.5 on 2021-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
