# Generated by Django 3.1.5 on 2021-01-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20210124_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
