# Generated by Django 3.1.5 on 2021-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
