# Generated by Django 3.1.5 on 2021-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_userprofile_is_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
