# Generated by Django 3.1.5 on 2021-01-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20210125_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usercat',
        ),
    ]
