# Generated by Django 3.1.5 on 2021-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_auto_20210126_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
